codecov:
  require_ci_to_pass: true
  branch: master

coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        target: 80%
        threshold: 5%
        if_ci_failed: error

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no
